# Generated by Django 4.1 on 2022-12-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_payment_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='card',
            field=models.CharField(max_length=19),
        ),
    ]
